README.md
README_ZH.md
notebook/how_to_deploy.md
workflow/andrew_translation_agent.yml
workflow/basic_rag_sample.yml

update readme for welcoming others' contribution

---

README.md
README_ZH.md

update readme for better documentation

---

README_ZH.md

remove useless part

---

README.md
README_ZH.md
workflow/marketing-copywriting.yml
workflow/rag_based_bot_with_tts.yml

add more workflows

---

README.md
README_ZH.md
model_provider/sagemaker/llm/llm.py
model_provider/sagemaker/sagemaker.yaml

support opensource model on dify

---

model_provider/sagemaker/llm/llm.py

fix LLM integration in docker env

---

README.md
README_ZH.md
workflow/simple_Kimi.yml

add simple_kimi workflow

---

dify.yaml

upgrade dify

---

workflow/simple_kimi.yml

update simple_kimi workflow

---

workflow/simple_kimi.yml

update simple kimi

---

.gitignore
README.md
README_ZH.md
builtin_tools/aws/tools/sagemaker_chinese_toxicity_detector.py
builtin_tools/aws/tools/sagemaker_chinese_toxicity_detector.yaml

None
add Chinese toxicity detector

add Chinese Toxicity Detector

---

builtin_tools/aws/tools/sagemaker_chinese_toxicity_detector.py

As model is trained again, and the response is changed as follow:
{
"body": {
"prediction": 1,
"probabilities": [
0.01971365325152874,
0.9802863001823425
]
},
"contentType": "application/json",
"invokedProductionVariant": "AllTraffic"
}
So we need to change the way we parse

[ref] Modify model response parser

---

workflow/README.md

update readme, use video instead of gif

---

README.md
README_ZH.md
builtin_tools/aws/tools/s3_operator.py
builtin_tools/aws/tools/s3_operator.yaml

add s3 tool

---

README.md
README_ZH.md
workflow/LLM-Finetuning-Dataflow-dify.yml

add llm finetune data Synthesis workflow

---

builtin_tools/aws/tools/nova_canvas.py
builtin_tools/aws/tools/nova_canvas.yaml
workflow/generate_image.yml

add nova canvas tools for generate image
suport text to image and image to image

add nova canvas for generate image

---

README.md
README_ZH.md
builtin_tools/aws/tools/nova_canvas.py
builtin_tools/aws/tools/nova_canvas.yaml
builtin_tools/aws/tools/nova_reel.py
builtin_tools/aws/tools/nova_reel.yaml
workflow/generate_image.yml
workflow/generate_video.yml

Add nova reel for generate videos
Support sync and async mode
Support text-to-video and image-to-video

add nova reel for generate videos

---

workflow/README.md

update demo page

---

workflow/eks_upgrade_planning/README.md
workflow/eks_upgrade_planning/README_zh.md
workflow/eks_upgrade_planning/eks_cluster_info.py
workflow/eks_upgrade_planning/eks_upgrade_planning.yml
workflow/eks_upgrade_planning/requirements.txt

Add the support of self-managed resources: 
- Self-managed nodes
- Karpenter nodes
- Self-managed addons

add self-managed resource support

---

README.md
README_ZH.md
notebook/bge-reranker-v2-m3-deploy.ipynb

dify utilized normlized score for reranker, hence adding result normalization.

update for BGE reranker model normalization

---

README.md
README_ZH.md
workflow/ASR_Transcribe.yml
workflow/README.md

add transcribe workflow and its demo video

---

README.md
README_ZH.md

added EKS upgrade planning demo

---

README.md
README_ZH.md
workflow/README.md
workflow/opensearch_img_search.yml

image2image text2image search workflow

---

README.md
README_JA.md
README_ZH.md
workflow/README.md

Yuanbo dev

---

notebook/search_img_by_img/image_search.ipynb
workflow/opensearch_img_search.yml

fix permission problem

---

plugins/aws_tools/manifest.yaml
plugins/aws_tools/requirements.txt
plugins/aws_tools/tools/translation_evaluator.py
plugins/aws_tools/tools/translation_evaluator.yaml

add translation evalutor tool

---

plugins/bedrock/models/llm/llm.py

fix: bedrock init for deepseek model id

---

plugins/aws_tools/provider/aws_tools.yaml
plugins/aws_tools/tools/invoke_code_interpreter.py
plugins/aws_tools/tools/invoke_code_interpreter.yaml

added agentcore code interpreter plugin

---

plugins/aws_tools/tools/agentcore-browser-tool.py
plugins/aws_tools/tools/agentcore-browser-tool.yaml

feat: browser delete screen_shot

---

plugins/aws_tools/provider/aws_tools.yaml
plugins/aws_tools/tools/agentcore_code_interpreter.py
plugins/aws_tools/tools/agentcore_code_interpreter.yaml

updated code interpreter
